version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  pypi-install:
    machine: true
    steps:
      - checkout
      - run:
          name: Installing OpenSSL
          command: sudo apt update && sudo apt install OpenSSL
      - run:
          name: Updating Pyenv
          command: cd /opt/circleci/.pyenv/plugins/python-build/../.. && git pull && cd -
      - run:
          name: Install Python
          command: pyenv install 3.9
      - run:
          name: Set Python Version
          #
          command: pyenv global 3.9
      - run:
          name: pypi
          command: pip install sumo-output-parsers
      - run:
          name: pypi
          command: pip install pytest pytest-resource-path
      - run:
          name: Run tests
          command: pytest tests
  package-build:
    machine: true
    steps:
      - checkout
      - run:
          name: Installing OpenSSL
          command: sudo apt update && sudo apt install OpenSSL
      - run:
          name: Updating Pyenv
          command: cd /opt/circleci/.pyenv/plugins/python-build/../.. && git pull && cd -
      - run:
          name: Install Python
          command: pyenv install 3.9
      - run:
          name: Set Python Version
          #
          command: pyenv global 3.9
      - run:
          name: install package dependencies
          command: pip install poetry && make install && pip install pytest pytest-resource-path
      - run:
          name: Run tests
          command: make test

workflows:
  tests:
    jobs:
      - package-build
      - pypi-install
