version: 2.1
workflows:
  version: 2
  tests:
    jobs:
      - pypiTest:
          name: "pypi 3.9"
          v: "3.9"
      - pypiTest:
          name: "pypi 3,8"
          v: "3.8"
      - installTest:
          name: "build 3.9"
          v: "3.9"
      - installTest:
          name: "build 3.8"
          v: "3.8"
jobs:
  pypiTest:
    parameters:
      v:
        type: string
        default: "latest"
      latest:
        type: boolean
        default: false
    docker:
      - image: "circleci/python:<< parameters.v >>"
    steps:
      - checkout
      - run:
          name: installing SUMO
          command: apt update && apt-get install -y software-properties-common && apt-get install -y software-properties-common && add-apt-repository -y ppa:sumo/stable && apt update && apt-get install -y sumo sumo-tools sumo-doc
      - run:
          name: pypi
          command: pip install sumo-output-parsers
      - run:
          name: pypi
          command: pip install pytest pytest-resource-path
      - run:
          name: Run tests
          command: pytest tests
  installTest:
    parameters:
      v:
        type: string
        default: "latest"
      latest:
        type: boolean
        default: false
    docker:
      - image: "circleci/python:<< parameters.v >>"
    steps:
      - checkout
      - run:
          name: installing SUMO
          command: apt update && apt-get install -y software-properties-common && apt-get install -y software-properties-common && add-apt-repository -y ppa:sumo/stable && apt update && apt-get install -y sumo sumo-tools sumo-doc
      - run:
          name: install package dependencies
          command: pip install poetry && pip install pytest pytest-resource-path
      - run:
          name: install the package
          command: poetry install
      - run:
          name: Run tests
          command: pytest tests/
