version: 2.1
workflows:
  tests:
    jobs:
      - pypi-3.8
      - pypi-3.9
      - install-3.8
      - install-3.9
orbs:
  python: circleci/python@1.2

jobs:
  pypi-3.8: &pypi-template
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: pypi
          command: pip install sumo-output-parsers
      - run:
          name: pypi
          command: pip install pytest pytest-resource-path
      - run:
          name: Run tests
          command: pytest tests
  install-3.8: &install-template
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: install package dependencies
          command: pip install poetry && make install && pip install pytest pytest-resource-path
      - run:
          name: Run tests
          command: make test
  pypi-3.9:
    <<: *pypi-template
    docker:
      - image: circleci/python:3.9
  install-3.9:
    <<: *install-template
    docker:
      - image: circleci/python:3.9

